Support spanish tokens in the UI
corsali/vana-portrait-demo pull request #33
Opened 2023-02-03 20:38 UTC by josephcsoti

### Description

Adds support (front-end) for the tokens:

```
yo
mi
mí
```

2023-02-03 21:03 UTC, Kahtaf requested changes
Thanks Joseph! I think we are almost there, one minor change.

2023-02-03 21:03 UTC, Kahtaf commented on config/regex.js
> +  REGEX_ES_MI2: /\bmí\b/i,
I think we are missing a version of mí. It doesn't seem to work with this mí, see Colin's Slack message: https://vana-org.slack.com/archives/C04MQM25YRK/p1675457705672829?thread_ts=1675457347.535289&cid=C04MQM25YRK

![image](https://user-images.githubusercontent.com/5796181/216710016-bf2a0fa6-846d-4832-9727-7bd025d73c19.png)

2023-02-03 21:03 UTC, Kahtaf commented on package.json
> +    "dev": "next dev -p 5333",
Let's not include the port change

2023-02-03 21:05 UTC, josephcsoti commented on package.json
> +    "dev": "next dev -p 5333",
whoops got sloppy with my `git add .` thnx

2023-02-06 20:05 UTC, josephcsoti commented
Test phrases

```
pintura al oleo de mí en la playa con 3 gatos bailando
pintura realista de mi en una sala de estar de los 1970 con un perro negro
yo parado en la calle durante una tormenta con un paraguas azul
```

2023-02-06 21:31 UTC, josephcsoti commented on config/regex.js
> +  REGEX_ES_MI2: /\bmí\b/i,
fixed regex (had to change it to a unicode version)

2023-02-08 19:48 UTC, Kahtaf approved these changes

2023-02-08 19:58 UTC, merged