Callum/van 488 text to image results UI
corsali/vana-portrait-demo pull request #8
Opened 2023-01-11 05:16 UTC by callumflack

2023-01-11 23:59 UTC, dmitryvlass commented
@callumflack , could you reduce this space for mobile?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/121915729/211943757-d7fbd693-02d7-4547-b985-be867ef8c04a.png">

2023-01-12 00:36 UTC, dmitryvlass commented
@callumflack , we were talking yesterday about the blinking images. It happens because we create multiple new user objects [here](https://github.com/corsali/vana-portrait-demo/blob/callum/van-488-text-to-image-results-ui/pages/index.js#L157)

So the user lifecycle looks next:
--- index.js renders 
1. Set the initial user
https://github.com/corsali/vana-portrait-demo/blob/callum/van-488-text-to-image-results-ui/pages/index.js#L21
2. Fetch the initial exhibits and rewrite the user object
--- refreshExhibits()
3. Create [the new user object](https://github.com/corsali/vana-portrait-demo/blob/callum/van-488-text-to-image-results-ui/pages/index.js#L124)

Because we update the reference to the user object, all dependent components also refresh, causing re-rendering of the whole DOM tree. It can be solved by using the primitives for the useState, updating only what has to be updated and passing only required data to the nested components.

2023-01-12 04:04 UTC, dmitryvlass requested changes

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/Generator.js
> +  }, [prompt])
You don't change `setValidPrompt` back when the prompt is valid. Could you handle the validation inside the <textarea onChange={handlePromptChange} ... /> ?

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/IdeasMessage.js
> +      <h2 className="">Stuck for ideas?</h2>
```suggestion
      <h2>Stuck for ideas?</h2>
```

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/IdeasMessage.js
> +      <p className="">Sometimes, all it takes is attention.</p>
```suggestion
      <p>Sometimes, all it takes is attention.</p>
```

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/IdeasMessage.js
> +      <p className="">
```suggestion
      <p>
```

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/IdeasMessage.js
> +        Still stuck? <a href="mailto:neil@vana.com" style={{ textDecoration: "underline"}}>Ask Neil.</a>{" "}
```suggestion
        Still stuck? <a href="mailto:neil@vana.com" style={{ textDecoration: "underline"}}>Ask Neil.</a>
```

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/PromptAwaitingMessage.js
> +      <h2 className="">Takes about a minute</h2>
```suggestion
      <h2>Takes about a minute</h2>
```

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/PromptAwaitingMessage.js
> +      <p className="">While you're waiting, here's some other ideas:</p>
```suggestion
      <p>While you're waiting, here's some other ideas:</p>
```

2023-01-12 04:04 UTC, dmitryvlass commented on components/prompt/PromptAwaitingMessage.js
> +      <p className="">
```suggestion
      <p>
```

2023-01-12 04:16 UTC, dmitryvlass commented on pages/index.js
> +      setTextToImageExhibitImages(images);
We need to reverse the images to show the last generated images on the top.

```suggestion
      setTextToImageExhibitImages(images.reverse());
```

2023-01-12 04:37 UTC, callumflack commented
@tnunamak @dmitryvlass heads up, I misunderstood how the Generator's `vanaPost` worked. So still have this todo:

- [ ] showing awaiting UI while `vanaPost` is running

2023-01-12 23:30 UTC, callumflack commented
Simple UI state when a user has not yet created any `textToImageExhibitImages`:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/749885/212203015-8b273c2b-99cc-4761-8b60-ea59c3cd205b.png">

2023-01-12 23:32 UTC, callumflack commented on components/prompt/Generator.js
> +    setTimeout(() => { setIsLoading(true) }, 1000);
@dmitryvlass based on chats about this, I misunderstood how `vanaPost('jobs/text-to-image')` worked. So we now know there's no reason to show a dialog at this point (the timeout above is related to this). So this is now deleted.

2023-01-13 00:34 UTC, dmitryvlass approved these changes

2023-01-13 00:37 UTC, merged